### ISSUE TITLE
Help wanted. Page id 0

### ISSUE THREAD

**Issue by willemdej** [marcfager/nspanel-mf#1]
Hello, I want to edit the first page to add some buttons on the right of the forecast, But where is it defined in the yaml file?

**Comment by marcfager** [comment]
Hi, please try the following:
- Open the .hmi file in Nextion Editor
- Add the buttons/objects you want to the screen
- Go through all objects by clicking them (one at a time) and check the following
  - Note the "id" number for the component
  - Note the "id" number for the page (visible on the left hand side of the page name. For the Home page this is 0)
  - In the Event box, check "Send component ID" both for the tab "Touch Press Event" and "Touch Release Event"
- Save the hmi file, and export it to .tft
- Upload the .tft to the NSPanel
- Add a section as per below under "binary_sensor:" for each button you created
`  - platform: nextion
    name: $device_name My new button
    page_id: 1 # Change 1 to the page ID. For Home it is 0. 
    component_id: 1 # Change 1 to the component ID.`
- Save & upload
- The button is now visible in Home Assistant. If you want, you can also directly attach a service call to it in the ESPHome config. Please see more [here](https://esphome.io/guides/automations.html).

**Comment by willemdej** [comment]
Thank you for your detailed explanation.
