### ISSUE TITLE
Factory restore for NSPanel

### ISSUE THREAD

**Issue by zeridon** [marcfager/nspanel-mf#10]
I am looking for a way to factory restore the NSPanel.

What i mean by factory restore is to flash the original HMI interface and the original BIN for the esp32.

Getting backup for the ESP is easy and i have done it. Now how to do the HMI/TFT part? or is there some place where i can get the original TFT. HMI would be much nicer but beggars can't be choosers.

**Comment by klausdm** [comment]
You will find all what you need in this thread. https://community.home-assistant.io/t/sonoff-nspanel-smart-scene-wall-switch-by-itead-coming-soon-on-kickstarter/332962/1

**Comment by zeridon** [comment]
I found the dumped tft but i was thinking for a procedure to dump the tft from the display. Any ideas where to hunt for that?

**Comment by marcfager** [comment]
I would check in the Nextion documentation if there are commands to download the tft file from the display. I do not know whether it is possible or not.
