### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by DieterKoblenz** [marcfager/nspanel-mf#11]
Foremost, thanks for sharing. This is awesome work. 

For reference, is it possible to disable the music page from ESPhome or HA? Or is this only possible in the HMI file?

Are you planning on adding more icons to support scenes instead of just lights? Currently, I'm using a modified version with some different icons I put in myself.

**Comment by marcfager** [comment]
Thank you.

Not as it is now, but you could do that in a similar way that the multiple light pages work. Add a (global) variable to control whether the music page is enabled or disabled. Set a default state to the default state you prefer (say 1 to enable it). When swiping left on the Home screen, before moving to the Music page, control what value the variable has. If it is in enable position (1), change page to Music. You can then control it by using the send command-service to set the variable 1 to enable the page or 0 to disable it. If you want to make it even simpler, you can add a service definition that changes the variable.

Regarding the icons I have just added the ones I use in my HA setup. I think it is challenging to cover all use cases so it is easier to just add what you need. :)

**Comment by DieterKoblenz** [comment]
Sweet. I'm closing the issue, as it isn't really one. I'll keep following this, especially for RGBW lightning.
