### ISSUE TITLE
Reqeust for sliders

### ISSUE THREAD

**Issue by larsoss** [marcfager/nspanel-mf#12]
Can you add sliders for light brightness?

**Comment by vingerha** [comment]
You can do this yourselves 'easily' by using the nextion editor
Add a slider (assume this gets objname: h0)
in the 'Touch Move' section, add: dim=h0.val

**Comment by marcfager** [comment]
Due to other priorities the development is slightly paused from my side, but as vingerha mentions, it is rather easy to add sliders with Nextion editor and to pick up the values in ESPHome.
