### ISSUE TITLE
unable to enter bootloader

### ISSUE THREAD

**Issue by sander816** [marcfager/nspanel-mf#18]
i have connected everything according to the manual, 3.3V, GND, RX and RX to 3.3V, GND RX and TX.
GPIO0 to GND.
But it is not entering bootloader. No connection in ESP home flasher. When i disconnect GPIO0 from GND, it starts correctly, as i can ping the ip adres of the device.
I completely removed the oard from the nspanel, so the serial connection is not touching the metal

**Comment by marcfager** [comment]
Hi,
I propose to ask in the thread in the HA forum for hardware support, as I am unfortunately not capable of helping out with that.
