### ISSUE TITLE
How do I swipe to next page?

### ISSUE THREAD

**Issue by Hellis81** [marcfager/nspanel-mf#19]
First off, this is fantastic!

I have managed to set up home screen and lights screen as I want.
Now I'm trying to set up lights2 or add any other screen to the right of Lights page?

I can't find where this order is set or where this is controlled.

**Comment by marcfager** [comment]
Hi,
Glad to hear you liked it!

Change the following in the very end of the ESPHome page. If you change the number to 2, the second page will be enabled. You add the lights by populating entities in the Lights2-page (see Nextion page for exact names for the positions).
        # Enable 1 light page (up to 4 available)
        - lambda: id(disp1).send_command_printf("Lights.pages.val=1");
