### ISSUE TITLE
Buzzer not working on NSPanel with ESPHOME

### ISSUE THREAD

**Issue by irqnet** [marcfager/nspanel-mf#30]
I've successfully flashed ESPHome on my NSPanel and adapted the settings for my personal needs with Homeassistant.

What I didn't get is, that the buzzer of my panel is not working with the following configuration:

`output:
  # Buzzer for playing tones
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21`

I haven't found any information about using another GPIO, so I assume using pin 21 should work, but I cannot get rttl tones played using the homeassistant service.

ESPHome Log:

![image](https://user-images.githubusercontent.com/32534199/196633269-1b06ecb4-3f77-498a-8367-a40f5b7911b7.png)

**Comment by nejc-cc** [comment]
I would check something isn't wrong hardware-wise. I just tested this and it works for me.

**Comment by irqnet** [comment]
Tried again with another NSPanel.. seems really hardware related.
