### ISSUE TITLE
Add image source files?

### ISSUE THREAD

**Issue by sublime93** [marcfager/nspanel-mf#6]
Would you be willing to share your source files for creating the images & button icons?

**Comment by marcfager** [comment]
Of course. However please clarify further what you are interested in. Do you want the png files that are included in the Nextion file, or are you interested in the "background material" used to create those? Is there some specific page or would you like to have everything?

I did the images in GIMP. My visual knowledge is very limited so the images are practically with one layer only. However I have saved some of the details (boxes etc) in separate files.

**Comment by sublime93** [comment]
I am interested in the source files with the layers, where I could easily swap out images and icons. I should be able to recreate something pretty easily. I also have very limited knowledge in GIMP,  typically I use photopea.
