### ISSUE TITLE
Possibility to send images?

### ISSUE THREAD

**Issue by suiciety** [marcfager/nspanel-mf#7]
Just a general query, for things like the notifications is it possible to send images to the panel? Use case would be thumbnails from a doorbell, media player covers or custom backgrounds. I understand there is limited ram and bandwidth to the panel.

**Comment by marcfager** [comment]
Unfortunately, I don't think it is possible. At least not easily. The panel supports choosing a picture among included ones but not adding external ones.

I have seen a [custom design](https://github.com/MMMZZZZ/Random-Stuff/tree/master/Nextion%20HSV%20Test) for choosing RGB colors from the HMI. This basically renders the color map on the HMI. I guess you could, theoretically, use a similar approach to draw an image on the HMI, but it is not straight forward.

**Comment by Shogun1978** [comment]
First of all: @marcfager amazing work! I just tested the display with another tutorial from youtube, but your solution is far more complete. Amazing work!
@topic: The .tft file seems to be pretty fixed. In the Nextion Editor I could find a lot of options, but no item that allows you to receive images.
