### ISSUE TITLE
upload firmware

### ISSUE THREAD

**Issue by wifi75** [marcfager/nspanel-mf#9]
Hello fter send  firmwar from esphome by HA there is this error:
![image](https://user-images.githubusercontent.com/31816231/152688172-6ca76336-8565-4985-8def-f420f51afd63.png)
what can I do?

I eneble nspanel Web Server and it work bit from esphome it is offline:
![image](https://user-images.githubusercontent.com/31816231/152688220-239727f6-81bd-41fd-9398-52148cff71fb.png)

**Comment by marcfager** [comment]
Hi,

Unfortunately, I do not know what causes this. I kindly suggest to ask in the [Home Assistant Forum thread](https://community.home-assistant.io/t/sonoff-nspanel-smart-scene-wall-switch-by-itead-coming-soon-on-kickstarter/332962/385).
